openapi: 3.2.0
info:
  title: Payments API V2 Recipient Emails API
  description: '# Introduction

    Payments API v2 enables payers to:

    - Create and manage recipients at an aggregator or payer level

    - Create and manage destination payment accounts at an aggregator or payer level

    - Create and manage payments for Portal acceptance

    - Create payout transactions for immediate disbursement


    # Idempotent Requests

    The API supports **Idempotency** for safely retrying requests without performing the same operation twice for **Create Payment** and **Create Transaction** endpoints.'
  contact: {}
  version: '2'
servers:
- url: http://example.com
  variables: {}
security:
- httpBearer: []
tags:
- name: Recipient Emails
paths:
  /api/v2/{payer_id}/recipients/{recipient_id}/emails:
    post:
      tags:
      - Recipient Emails
      summary: Add Recipient Email
      operationId: AddRecipientEmail
      parameters:
      - name: payer_id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      - name: recipient_id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddRecipientEmailRequest'
            example:
              email: payee-123456@mailinator.com
              primary: false
        required: true
      responses:
        '200':
          description: OK
          headers:
            X-Content-Type-Options:
              content:
                text/plain:
                  schema:
                    type: string
                    example: nosniff
                  example: nosniff
            X-XSS-Protection:
              content:
                text/plain:
                  schema:
                    type: string
                    example: 1; mode=block
                  example: 1; mode=block
            Cache-Control:
              content:
                text/plain:
                  schema:
                    type: string
                    example: no-cache, no-store, max-age=0, must-revalidate
                  example: no-cache, no-store, max-age=0, must-revalidate
            Pragma:
              content:
                text/plain:
                  schema:
                    type: string
                    example: no-cache
                  example: no-cache
            Expires:
              content:
                text/plain:
                  schema:
                    type: string
                    example: '0'
                  example: '0'
            X-Frame-Options:
              content:
                text/plain:
                  schema:
                    type: string
                    example: DENY
                  example: DENY
            Set-Cookie:
              content:
                text/plain:
                  schema:
                    type: string
                    example: SESSION=ZmJkYTY2MDktYTJkZC00ZWRhLWJhYmEtMGRjZjk2YTBmNTAz; Path=/; HttpOnly; SameSite=Lax
                  example: SESSION=ZmJkYTY2MDktYTJkZC00ZWRhLWJhYmEtMGRjZjk2YTBmNTAz; Path=/; HttpOnly; SameSite=Lax
            Content-Length:
              content:
                text/plain:
                  schema:
                    type: string
                    example: '0'
                  example: '0'
            Date:
              content:
                text/plain:
                  schema:
                    type: string
                    example: Mon, 11 Oct 2021 21:53:29 GMT
                  example: Mon, 11 Oct 2021 21:53:29 GMT
            Keep-Alive:
              content:
                text/plain:
                  schema:
                    type: string
                    example: timeout=60
                  example: timeout=60
            Connection:
              content:
                text/plain:
                  schema:
                    type: string
                    example: keep-alive
                  example: keep-alive
          content: {}
      deprecated: false
    get:
      tags:
      - Recipient Emails
      summary: Get Recipient Emails
      operationId: GetRecipientEmails
      parameters:
      - name: payer_id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      - name: recipient_id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: OK
          headers:
            X-Content-Type-Options:
              content:
                text/plain:
                  schema:
                    type: string
                    example: nosniff
                  example: nosniff
            X-XSS-Protection:
              content:
                text/plain:
                  schema:
                    type: string
                    example: 1; mode=block
                  example: 1; mode=block
            Cache-Control:
              content:
                text/plain:
                  schema:
                    type: string
                    example: no-cache, no-store, max-age=0, must-revalidate
                  example: no-cache, no-store, max-age=0, must-revalidate
            Pragma:
              content:
                text/plain:
                  schema:
                    type: string
                    example: no-cache
                  example: no-cache
            Expires:
              content:
                text/plain:
                  schema:
                    type: string
                    example: '0'
                  example: '0'
            X-Frame-Options:
              content:
                text/plain:
                  schema:
                    type: string
                    example: DENY
                  example: DENY
            Set-Cookie:
              content:
                text/plain:
                  schema:
                    type: string
                    example: SESSION=OWQ2MWZlZWQtZjQwYS00NzFhLTk3NmYtNjg3MWE3ZmYxZjFi; Path=/; HttpOnly; SameSite=Lax
                  example: SESSION=OWQ2MWZlZWQtZjQwYS00NzFhLTk3NmYtNjg3MWE3ZmYxZjFi; Path=/; HttpOnly; SameSite=Lax
            Transfer-Encoding:
              content:
                text/plain:
                  schema:
                    type: string
                    example: chunked
                  example: chunked
            Date:
              content:
                text/plain:
                  schema:
                    type: string
                    example: Mon, 11 Oct 2021 21:53:50 GMT
                  example: Mon, 11 Oct 2021 21:53:50 GMT
            Keep-Alive:
              content:
                text/plain:
                  schema:
                    type: string
                    example: timeout=60
                  example: timeout=60
            Connection:
              content:
                text/plain:
                  schema:
                    type: string
                    example: keep-alive
                  example: keep-alive
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetRecipientEmail'
                description: ''
                example:
                - email: payee-123456@mailpoof.com
                  primary: true
                  invalid: false
                - email: payee-123456@mailinator.com
                  primary: false
                  invalid: false
              example:
              - email: payee-123456@mailpoof.com
                primary: true
                invalid: false
              - email: payee-123456@mailinator.com
                primary: false
                invalid: false
      deprecated: false
components:
  schemas:
    GetRecipientEmail:
      title: GetRecipientEmail
      required:
      - email
      - primary
      - invalid
      type: object
      properties:
        email:
          type: string
        primary:
          type: boolean
        invalid:
          type: boolean
      example:
        email: payee-123456@mailpoof.com
        primary: true
        invalid: false
    AddRecipientEmailRequest:
      title: AddRecipientEmailRequest
      required:
      - email
      - primary
      type: object
      properties:
        email:
          type: string
        primary:
          type: boolean
      example:
        email: payee-123456@mailinator.com
        primary: false
  securitySchemes:
    httpBearer:
      type: http
      scheme: bearer
