openapi: 3.2.0
info:
  title: Payments API V2 Recipient Verification API
  description: '# Introduction

    Payments API v2 enables payers to:

    - Create and manage recipients at an aggregator or payer level

    - Create and manage destination payment accounts at an aggregator or payer level

    - Create and manage payments for Portal acceptance

    - Create payout transactions for immediate disbursement


    # Idempotent Requests

    The API supports **Idempotency** for safely retrying requests without performing the same operation twice for **Create Payment** and **Create Transaction** endpoints.'
  contact: {}
  version: '2'
servers:
- url: http://example.com
  variables: {}
security:
- httpBearer: []
tags:
- name: Recipient Verification
paths:
  /api/v2/{payer_id}/recipients/{recipient_id}/verification:
    post:
      tags:
      - Recipient Verification
      summary: Verify Recipient TIN
      operationId: VerifyRecipientTIN
      parameters:
      - name: payer_id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      - name: recipient_id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyRecipientTINRequest'
            example:
              tin: '123456789'
              address:
                address_1: 134 N 4th St
                city: Brooklyn
                state: NY
                zip: '11249'
              legal_entity_type: INDIVIDUAL
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    get:
      tags:
      - Recipient Verification
      summary: Get Recipient TIN Verification
      operationId: GetRecipientTINVerification
      parameters:
      - name: payer_id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      - name: recipient_id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
components:
  schemas:
    Address:
      title: Address
      required:
      - address_1
      - city
      - state
      - zip
      type: object
      properties:
        address_1:
          type: string
        city:
          type: string
        state:
          type: string
        zip:
          type: string
      example:
        address_1: 134 N 4th St
        city: Brooklyn
        state: NY
        zip: '11249'
    VerifyRecipientTINRequest:
      title: VerifyRecipientTINRequest
      required:
      - tin
      - address
      - legal_entity_type
      type: object
      properties:
        tin:
          type: string
        address:
          $ref: '#/components/schemas/Address'
        legal_entity_type:
          type: string
      example:
        tin: '123456789'
        address:
          address_1: 134 N 4th St
          city: Brooklyn
          state: NY
          zip: '11249'
        legal_entity_type: INDIVIDUAL
  securitySchemes:
    httpBearer:
      type: http
      scheme: bearer
